Guides 2.0 - Actions# Request and Response objects
hanami/guides pull request #117
Opened 2022-11-16 16:49 UTC by swilgosz

Resolves: https://trello.com/c/nHBWjfbd/299-actions-request-and-response-objects

Extracted each of the sections of https://github.com/hanami/guides/pull/101 to the separate PR for easier merging process, and review.

2022-11-16 16:51 UTC, swilgosz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Actions: request and response objects](https://trello.com/c/nHBWjfbd/299-actions-request-and-response-objects)

2022-11-21 04:53 UTC, solnic requested changes

2022-11-21 04:53 UTC, solnic commented on content/v2.0/actions/request-and-response.md
> +In order to access the metadata coming from a HTTP request, an action has a private object `request` that derives from `Rack::Request`.
```suggestion
In order to access the metadata coming from an HTTP request, an action has a private object called `request`.
```

Feels like too much info about implementation details so better to keep it simple.

2022-11-21 04:53 UTC, solnic commented on content/v2.0/actions/request-and-response.md
> +Here an example of some information that we can introspect.
```suggestion
Here's an example of information that we can get from the request object.
```

2022-11-21 04:53 UTC, solnic commented on content/v2.0/actions/request-and-response.md
> +As an addition to a request, we have a `response` object to our disposal, which derives from `Rack::Response`
```suggestion
Next to the request object, we also have the `response` object, which can be used to return an HTTP response.
```

2022-11-21 04:53 UTC, solnic commented on content/v2.0/actions/request-and-response.md
> +
empty line

2022-11-21 04:53 UTC, solnic commented on content/v2.0/actions/request-and-response.md
> +# It will return [201, { "X-Custom" => "OK" }, ["Your resource has been created"]]
```suggestion
# It will return the follow rack response:
#
# [201, { "X-Custom" => "OK" }, ["Your resource has been created"]]
```

2022-11-21 08:02 UTC, timriley approved these changes
It's good!

2022-11-21 08:02 UTC, timriley commented on content/v2.0/actions/request-and-response.md
> +When a Hanami action is invoked, the incoming HTTP request and outgoing HTTP response are represented by the `request` and `response` objects provided as arguments to the action's `#handle` method.
```suggestion
When a Hanami action is called, the incoming HTTP request and outgoing HTTP response are represented by the `request` and `response` objects provided to the action's `#handle` method.
```

2022-11-21 08:51 UTC, andrewcroome approved these changes

2022-11-21 08:53 UTC, merged