Guides 2.0 - Actions # Exception Handling
hanami/guides pull request #118
Opened 2022-11-16 17:00 UTC by swilgosz

Resolves: https://trello.com/c/7NLrGDMo/300-actions-exception-handling

Extracted from: https://github.com/hanami/guides/pull/101

2022-11-16 17:00 UTC, swilgosz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Actions: exception handling](https://trello.com/c/7NLrGDMo/300-actions-exception-handling)

2022-11-21 06:28 UTC, solnic requested changes

2022-11-21 06:28 UTC, solnic commented on content/v2.0/actions/exception-handling.md
> +Actions have an elegant API for exception handling. You can define the exception handling per action, using app/slice configuration.
```suggestion
When a request crashes with an exception, you want to handle it in a graceful manner. In order to do this, you can use the `handle_exception` action API.
```

2022-11-21 06:28 UTC, solnic commented on content/v2.0/actions/exception-handling.md
> +By default, actions do not handle errors risen by the app, and to handle them, you need to define the error mapping to the handler.
```suggestion
By default, actions do not handle exceptions raised by the app. To handle them, you need to define how a specific exception type should be translated into an HTTP response.
```

2022-11-21 06:28 UTC, solnic commented on content/v2.0/actions/exception-handling.md
> +In our example, when `StandardError` is raised, it will be handled as a `500` (Server Error).
```suggestion
In our example, when `StandardError` is raised, it will be handled as a `500` (Server Error) response.
```

2022-11-21 06:28 UTC, solnic commented on content/v2.0/actions/exception-handling.md
> +If the mapping with a custom HTTP status doesn't fit our needs, we can specify a custom handler and manage the exception by ourselves.
```suggestion
If the mapping with a custom HTTP status doesn't fit your needs, you can specify a custom handler and manage the exception by yourself.
```

2022-11-21 06:28 UTC, solnic commented on content/v2.0/actions/exception-handling.md
> +        def my_error_handler(req, res, exception)
```suggestion
        def my_error_handler(request, response, exception)
```

2022-11-21 06:28 UTC, solnic commented on content/v2.0/actions/exception-handling.md
> +This time, when `StandardError` will be raised, it'll be handled by our method.
```suggestion
This time, when `StandardError` is raised, it'll be handled by our method.
```

2022-11-21 12:17 UTC, timriley approved these changes
Looks good! Just a couple minor wordy bits

2022-11-21 12:17 UTC, timriley commented on content/v2.0/actions/exception-handling.md
> +When a request crashes with an exception, you want to handle it in a graceful manner. In order to do this, you can use the `handle_exception` action API.
```suggestion
When a request crashes with an exception, you may want to handle it in a graceful manner. To do this, you can use `handle_exception` in your actions.
```

2022-11-21 12:17 UTC, timriley commented on content/v2.0/actions/exception-handling.md
> +In the above action, when `StandardError` is raised in the `#handle` method, a `500 Internal Server Error` will be returned.
```suggestion
In the above action, when `StandardError` is raised in the `#handle` method, a basic `500 Internal Server Error` will be returned.
```

![giphy](https://user-images.githubusercontent.com/3134/203051483-cf4de175-1166-493d-b095-47435502ca0c.gif)

2022-11-21 12:17 UTC, timriley commented on content/v2.0/actions/exception-handling.md
> +This time, when `StandardError` is raised, the `#handle_standard_error` will render a json response.
```suggestion
Here, when `StandardError` is raised, `#handle_standard_error` will prepare a JSON response.
```

2022-11-21 12:18 UTC, timriley reviewed
I think we can remove `content/v2.0/actions/customized-error-response.png` from this PR — it doesn't seem to be referenced in this file anymore.

2022-11-21 12:24 UTC, andrewcroome commented on content/v2.0/actions/exception-handling.md
> +In the above action, when `StandardError` is raised in the `#handle` method, a `500 Internal Server Error` will be returned.
lol @timriley

2022-11-21 12:30 UTC, merged