Guides 2.0 - Actions # Rack middleware
hanami/guides pull request #120
Opened 2022-11-16 17:09 UTC by swilgosz

Resolves: https://trello.com/c/01yOPtHU/307-actions-rack-middleware

Extracted from: https://github.com/hanami/guides/pull/101

2022-11-16 17:09 UTC, swilgosz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Actions: rack middleware](https://trello.com/c/01yOPtHU/307-actions-rack-middleware)

2022-11-21 06:13 UTC, solnic requested changes

2022-11-21 06:13 UTC, solnic commented on content/v2.0/actions/rack-integration.md
> +## Project Middleware
I'm confused by this header. What does Project refer to exactly?

2022-11-21 06:13 UTC, solnic commented on content/v2.0/actions/rack-integration.md
> +The difference is that the  `app`  configuration is shared across all slices.
```suggestion
The difference is that the `app` configuration is shared across all slices.
```

2022-11-22 11:58 UTC, merged