Docs: Guides 2.0 - routes
hanami/guides pull request #99
Opened 2021-12-21 18:17 UTC by swilgosz

### Overview

Routes explanation for guides 2.0

- [x] Overview
- [x] Basic Usage
- [x] Advanced Usage
- [  ] Testing

Relates to: #97

2022-05-25 13:39 UTC, swilgosz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Hanami-Guides: Router](https://trello.com/c/hWSRlmit/137-hanami-guides-router)

2022-11-21 06:40 UTC, solnic requested changes
I've left some suggestions. On top of this, please pay attention to "we" vs "you" because it's inconsistent right now (here and in other guides). My understanding is that we want to always refer to "you" (the reader). So, ie "If you want to do X" rather than "If we want to do X".

2022-11-21 06:40 UTC, solnic commented on content/v2.0/router/advanced-usage.md
> +In Hanami, you can mount any rack application in desired route. If we want to do it, you should use the `mount` keyword.
```suggestion
In Hanami, you can mount any rack application under desired route, in order to do it, you can use `mount` method:
```

2022-11-21 06:40 UTC, solnic commented on content/v2.0/router/advanced-usage.md
> +The former is for plural resources, the latter for singular ones.
I feel like this sentence is not needed.

2022-11-21 06:40 UTC, solnic commented on content/v2.0/router/advanced-usage.md
> +### Remove Routes
```suggestion
### Excluding RESTful routes
```

2022-11-21 06:40 UTC, solnic commented on content/v2.0/router/advanced-usage.md
> +### Add Routes
```suggestion
### Adding Routes
```

2022-11-21 06:40 UTC, solnic commented on content/v2.0/router/advanced-usage.md
> +Alongside with default routes we can specify extra routes for single (`member`) or multiple (`collection`) resources.
```suggestion
Alongside the default routes we can specify extra routes for single (`member`) or multiple (`collection`) resources.
```

2022-12-17 20:35 UTC, swilgosz commented
Closing, as routing is already deployed with another PR.

2022-12-17 20:35 UTC, closed without merging